[[constraint]]
  branch = "pkcs12"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "certificateutil"
  name = "github.com/bitrise-tools/go-xcode"

[[constraint]]
  branch = "has_scheme"
  name = "github.com/bitrise-tools/xcode-project"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "software.sslmate.com/src/go-pkcs12"

[prune]
  go-tests = true
  unused-packages = true
