
[[constraint]]
  name = "github.com/bitrise-io/bitrise-add-new-project"
  version = "0.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "project-attribute"
  name = "github.com/bitrise-io/xcode-project"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/google/go-querystring"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "howett.net/plist"

[prune]
  go-tests = true
  unused-packages = true
