[[constraint]]
  branch = "pkcs12"
  name = "github.com/bitrise-io/go-utils"

[[constraint]]
  branch = "TOOL-915-support-multiple-identities-in-p12"
  name = "github.com/bitrise-tools/go-xcode"

[[constraint]]
  branch = "has_scheme"
  name = "github.com/bitrise-tools/xcode-project"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
